### ISSUE TITLE
Home: increase padding in search input

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-www#102]
When you enter text in the search form on the home page, it's too close to the left edge of the input field. 

Currently: 

![image (11)](https://user-images.githubusercontent.com/430126/116463298-88b30280-a838-11eb-9836-556cfe6a3f57.png)

With 12px of left padding:  

<img alt="image" src="https://user-images.githubusercontent.com/430126/116463459-b4ce8380-a838-11eb-8da4-ebdd6a650110.png">

**Comment by abdulkdawson** [comment]
Here is a mock of what the spacing in the search box should look like. 12px of padding on the left of the input text. 
![Uploading image.png…]()
