### ISSUE TITLE
Update Give now and Learn More button text color

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/ocw-www#105]
Change the current Give Now, Give and Learn More button text
[Link to InVision project](https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/448296968/preview?scrollOffset=0)

Old Give Now Button
<img width="733" alt="Screen Shot 2021-04-29 at 5 08 51 PM" src="https://user-images.githubusercontent.com/49685474/116618853-a30ae000-a90d-11eb-9de4-cfe844e63594.png">

New Give Now Button
<img width="748" alt="Screen Shot 2021-04-29 at 4 47 33 PM" src="https://user-images.githubusercontent.com/49685474/116618905-b7e77380-a90d-11eb-8249-00ba25860b11.png">
Background: #FF8A1F , Text:#000000

Old Learn More Button
<img width="737" alt="Screen Shot 2021-04-29 at 5 08 57 PM" src="https://user-images.githubusercontent.com/49685474/116618923-c33a9f00-a90d-11eb-9fdd-c74b531b37d0.png">

New Learn More Button
<img width="696" alt="Screen Shot 2021-04-29 at 4 47 38 PM" src="https://user-images.githubusercontent.com/49685474/116618949-cd5c9d80-a90d-11eb-9892-f1490c2360b1.png">
Background: #FF8A1F , Text:#000000

Old Give Button /w Heart Icon
<img width="728" alt="Screen Shot 2021-04-29 at 5 09 02 PM" src="https://user-images.githubusercontent.com/49685474/116618984-db122300-a90d-11eb-9172-28d456dbad56.png">

New Give Button /w Heart Icon
<img width="764" alt="Screen Shot 2021-04-29 at 5 11 30 PM" src="https://user-images.githubusercontent.com/49685474/116619061-f5e49780-a90d-11eb-9cb4-fc1fcb43c4dd.png">
Background: #000000, Text:#FF8A1F

**Comment by abdulkdawson** [comment]
@noisecapella We should use the same "Learn More" button and have it align left with the text above.

**Comment by noisecapella** [comment]
@abdulkdawson There is sometimes other text in that carousel, for example "Enroll Now": 
![Screenshot from 2021-05-20 08-59-15](https://user-images.githubusercontent.com/863262/118983341-503fa980-b94a-11eb-80c3-2ecc1714a295.png)

Should I use "Learn More" or should I use whatever text was used there before in the orange button?

**Comment by abdulkdawson** [comment]
@noisecapella I completely forgot about this one. On second thought let's leave these as links. Can we increase the text size of the links as well?

**Comment by noisecapella** [comment]
@abdulkdawson How does the font size look here? 
![Screenshot from 2021-05-20 16-32-13](https://user-images.githubusercontent.com/863262/119045068-fad6bd00-b988-11eb-91e7-1f9f11877396.png)
