### ISSUE TITLE
publish instructors

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-www#126]
In the interim while we are using this repo as a content source for the `ocw-www` website, we will need to add a copy of the instructors now being published by `ocw-studio` at https://github.mit.edu/ocw-content-rc/ocw-www/tree/main/content/instructors in order to start testing static JSON API functionality.

**Comment by pdpinch** [comment]
Can this be closed?

**Comment by gumaerc** [comment]
@pdpinch Yep, this is no longer necessary as we're using the API published by `ocw-studio`
