### ISSUE TITLE
Search: topics overflow onto course image

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/ocw-www#13]
Link to Issue: https://github.com/mitodl/ocw-course-hugo-theme/issues/96

The Topics are overflowing into the image and it is hard to read as there are no commas separating each topic. 
We should add commas to the end of each topic as well as style the Topics by adding an underline to each one.
Also, can we add 16px of space between the topics section and the course image as diagrammed in the screenshot?
Lastly, can we remove the (s) from the current "Topics" section on the course card and just rename it "Topics".

<img width="751" alt="Screen Shot 2020-11-23 at 3 18 11 PM" src="https://user-images.githubusercontent.com/49685474/100010998-1b89d580-2d9f-11eb-8ce4-1622dcaa10e1.png">

**Comment by pdpinch** [comment]
This particular card only shows two topics now: 

from https://ocwnext.odl.mit.edu/search/?q=%2018.06sc

<img width="722" alt="image" src="https://user-images.githubusercontent.com/430126/113426054-e589dd00-93a0-11eb-9123-250e6d62f493.png">

There are still cards with too many topics, for example these two, from https://ocwnext.odl.mit.edu/search/?q=%22Ali%20Beyzavi%22

<img width="727" alt="image" src="https://user-images.githubusercontent.com/430126/113480098-a28f3e80-9460-11eb-8de5-cf4e47ff829c.png">

**Comment by pdpinch** [comment]
replaced by https://github.com/mitodl/ocw-course-hugo-theme/issues/96
