### ISSUE TITLE
Allow the site to run without OCW studio

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-www#22]
From [Ferdi](https://github.com/mitodl/ocw-www/pull/21#discussion_r558477895): 

> ocw studio should not be a dependency. News and New courses depend on it only. Ideally, if ocw studio is down, we'd simly not see those 2 carousels

If you try to run this locally without specifying a valid URL for a running OCW Studio instance, you get this error:
```
> hugo-course-publisher@1.5.0 start /Users/gavin/dev/ocw-www
> run-p start:**


> hugo-course-publisher@1.5.0 start:webpack /Users/gavin/dev/ocw-www
> webpack-dev-server --config src/webpack/webpack.dev.js --hot --host 0.0.0.0


> hugo-course-publisher@1.5.0 start:hugo /Users/gavin/dev/ocw-www
> hugo server -s site -p 3000 --bind 0.0.0.0 --renderToDisk

Start building sites …
ERROR 2021/01/15 13:12:02 Failed to get JSON resource "http://localhost:1234/api/websites/?type=course": Get "http://localhost:1234/api/websites/?type=course": dial tcp [::1]:1234: connect: connection refused
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
ERROR 2021/01/15 13:12:02 Failed to get JSON resource "http://localhost:1234/api/news/": Get "http://localhost:1234/api/news/": dial tcp [::1]:1234: connect: connection refused
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Built in 23 ms
Error: Error building site: logged 2 error(s)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! hugo-course-publisher@1.5.0 start:hugo: `hugo server -s site -p 3000 --bind 0.0.0.0 --renderToDisk`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the hugo-course-publisher@1.5.0 start:hugo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gavin/.npm/_logs/2021-01-15T18_12_02_616Z-debug.log
ERROR: "start:hugo" exited with 255.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hugo-course-publisher@1.5.0 start: `run-p start:**`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hugo-course-publisher@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gavin/.npm/_logs/2021-01-15T18_12_02_679Z-debug.log
```

**Comment by Ferdi** [comment]
Is there any other way to make fails a bit more graceful ?

**Comment by Ferdi** [comment]
e.g. https://discourse.gohugo.io/t/handling-getjson-errors-in-shortcodes/18597/3
@mbertrand @noisecapella

**Comment by noisecapella** [comment]
I don't think there is any way to make getJSON fail gracefully except by `ignoreErrors = ["error-remote-getjson"]` as @gumaerc mentioned. Should we have it fail on deployments if the URL doesn't resolve correctly, or should it show a blank area instead of OCW News or the course carousel?

**Comment by aliceriot** [comment]
I think we want different things in different environments - personally I want the `ignoreErrors = ["error-remote-getjson"]` setting in development but for production deploy we certainly don't want it

**Comment by noisecapella** [comment]
It should be straightforward to have different config files, but we also need some setup instructions or a build script for local development. I'm not sure how difficult that is since things are scattered in this repo, ocw-course-hugo-starter and ocw-course-hugo-theme.

Also, @pdpinch @Ferdi can we confirm that we want the deployment for production and RC to fail if OCW Studio does not respond or returns an error message? I think that makes sense personally since otherwise we randomly switch between having a news section and not having one

**Comment by pdpinch** [comment]
I agree with George that the _production build_ should break if the News API is unavailable, but dev builds should be more resilient. And the _production site_ needs to be resilient as well. 

@Ferdi ?

**Comment by noisecapella** [comment]
This is already done:
![Screenshot from 2021-06-17 12-35-59](https://user-images.githubusercontent.com/863262/122438324-96e3ec00-cf68-11eb-823d-6124aa984718.png)
