### ISSUE TITLE
Home: mobile styling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-www#23]
Looks like we lost some of our responsive styling on https://ocw-www--ocw-next.netlify.app/

<img width="562" alt="image" src="https://user-images.githubusercontent.com/430126/104764069-de094f00-5734-11eb-8c91-cee908b10f6d.png">

#### Designs and Mockups

InVision: https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/437726301/preview?scrollOffset=0

#### Acceptance Criteria:

- [ ] header (hero image, search box, learn more box)
- [ ] give section
- [ ] testimonials

**Comment by aliceriot** [comment]
actually already had a branch locally where I was fixing this, will open a bugfix pr shortly

**Comment by pdpinch** [comment]
Thanks for #25 Alice, what's left? It seems like the search box doesn't match InVision.

**Comment by aliceriot** [comment]
search box, testimonials, some other little things
