### ISSUE TITLE
env values in .env don't get passed to Hugo

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-www#30]
### Steps to Reproduce

Set `SEARCH_API_URL` or `OCW_STUDIO_BASE_URL` in a .env file and run `npm start`

### Expected Behavior

These values are passed along to Hugo for its build context

### Actual Behavior

They are not passed in, the only way to get it to work is to export the values

**Comment by aliceriot** [comment]
I think some changes I have in #26 will fix this
