### ISSUE TITLE
Update search page styling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-www#64]
#### Designs and Mockups

Desktop: https://projects.invisionapp.com/d/#/console/18609637/447781241/preview
Mobile: coming soon

#### Acceptance Criteria:

- [ ] Less white space at top
- [ ] New header text 
- [ ] courses/resources tab style
- [ ] Style filter buttons and clear all link per https://projects.invisionapp.com/d/#/console/18609637/447781243/preview and  https://projects.invisionapp.com/d/#/console/18609637/447781242/preview
- [ ] Accessibility for forms (labels, etc.)
- [ ] update search box/button

#### Out of Scope

- Not going to do

**Comment by noisecapella** [comment]
@pdpinch does this cover the search box too? This is what it looks like currently:
![Screenshot from 2021-03-22 10-26-28](https://user-images.githubusercontent.com/863262/112005532-3bd16300-8af9-11eb-8f42-02508da57fd9.png)

and the mockup:
![Screenshot from 2021-03-22 10-27-27](https://user-images.githubusercontent.com/863262/112005556-41c74400-8af9-11eb-94ea-60bac082a336.png)

**Comment by pdpinch** [comment]
Yes please.

> does this cover the search box too?

**Comment by noisecapella** [comment]
@pdpinch what happens when a user clicks the spyglass in the header?

**Comment by pdpinch** [comment]
Sorry, that shouldn't be there. Like the home page, there shouldn't be a search icon.
